name: Test

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Test
      uses: b4b4r07/github-search-templater@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      with:
        template: |
          ## Active repositories
          
          {{ range . }}
          ### {{ .Name }}
          
          {{ .Description }}
          
          {{ .URL }}
          {{ end }}
