name: Test

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Test
      uses: b4b4r07/github-search-templater@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        template: |
          ## Active repositories
          
          {{ range . }}
          ### {{ .Name }}
          
          {{ .Description }}
          
          {{ .URL }}
          {{ end }}
        query: 'topic:bash user:b4b4r07'
        repo: 'b4b4r07/github-search-templater'
        filepath: 'README.md'
        author: 'b4b4r07'
        email: 'b4b4r07@gmail.com'
        prbody: '## what\n## why'

        # filepath: 'docs/microservices-platform/references/github-repositories-we-maintain.md'
